ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD';

/* 주문정보 */
DROP TABLE ORDS 
	CASCADE CONSTRAINTS;

/* 제품사진정보 */
DROP TABLE PROD_PHOS 
	CASCADE CONSTRAINTS;

/* 고객정보 */
DROP TABLE CUSTS 
	CASCADE CONSTRAINTS;

/* 제품정보 */
DROP TABLE PRODS 
	CASCADE CONSTRAINTS;

/* 주소기본정보 */
DROP TABLE ADDRS 
	CASCADE CONSTRAINTS;

/* 고객추가정보 */
DROP TABLE CUST_EX 
	CASCADE CONSTRAINTS;

/* 주문정보 */
CREATE TABLE ORDS (
	O_NO INTEGER NOT NULL, /* 주문일련번호 */
	C_ID VARCHAR2(20) NOT NULL, /* 고객아이디 */
	P_NO INTEGER NOT NULL, /* 제품일련번호 */
	QNT INTEGER NOT NULL, /* 주문수량 */
	ORD_DT DATE DEFAULT sysdate /* 주문일 */
);

CREATE UNIQUE INDEX PK_ORDS
	ON ORDS (
		O_NO ASC
	);

ALTER TABLE ORDS
	ADD
		CONSTRAINT PK_ORDS
		PRIMARY KEY (
			O_NO
		);

COMMENT ON TABLE ORDS IS '주문정보';

COMMENT ON COLUMN ORDS.O_NO IS '주문일련번호';

COMMENT ON COLUMN ORDS.C_ID IS '고객아이디';

COMMENT ON COLUMN ORDS.P_NO IS '제품일련번호';

COMMENT ON COLUMN ORDS.QNT IS '주문수량';

COMMENT ON COLUMN ORDS.ORD_DT IS '주문일';

/* 제품사진정보 */
CREATE TABLE PROD_PHOS (
	PP_NO INTEGER NOT NULL, /* 사진일련번호 */
	P_NO INTEGER NOT NULL, /* 제품일련번호 */
	FLE_PAT VARCHAR2(255) NOT NULL /* 사진파일경로 */
);

CREATE UNIQUE INDEX PK_PROD_PHOS
	ON PROD_PHOS (
		PP_NO ASC
	);

ALTER TABLE PROD_PHOS
	ADD
		CONSTRAINT PK_PROD_PHOS
		PRIMARY KEY (
			PP_NO
		);

COMMENT ON TABLE PROD_PHOS IS '제품사진정보';

COMMENT ON COLUMN PROD_PHOS.PP_NO IS '사진일련번호';

COMMENT ON COLUMN PROD_PHOS.P_NO IS '제품일련번호';

COMMENT ON COLUMN PROD_PHOS.FLE_PAT IS '사진파일경로';

/* 고객정보 */
CREATE TABLE CUSTS (
	C_ID VARCHAR2(20) NOT NULL, /* 고객아이디 */
	PWD VARCHAR2(10) NOT NULL, /* 암호 */
	EMAIL VARCHAR2(40) NOT NULL, /* 이메일 */
	C_NM VARCHAR2(60) NOT NULL, /* 고객명 */
	TEL VARCHAR2(30) NOT NULL, /* 전화 */
	DET_ADDR VARCHAR2(255), /* 상세주소 */
	A_NO INTEGER /* 주소기본일련번호 */
);

CREATE UNIQUE INDEX PK_CUSTS
	ON CUSTS (
		C_ID ASC
	);

CREATE UNIQUE INDEX UIX_CUSTS
	ON CUSTS (
		EMAIL ASC
	);

ALTER TABLE CUSTS
	ADD
		CONSTRAINT PK_CUSTS
		PRIMARY KEY (
			C_ID
		);

ALTER TABLE CUSTS
	ADD
		CONSTRAINT UK_CUSTS
		UNIQUE (
			EMAIL
		);

COMMENT ON TABLE CUSTS IS '고객정보';

COMMENT ON COLUMN CUSTS.C_ID IS '고객아이디';

COMMENT ON COLUMN CUSTS.PWD IS '암호';

COMMENT ON COLUMN CUSTS.EMAIL IS '이메일';

COMMENT ON COLUMN CUSTS.C_NM IS '고객명';

COMMENT ON COLUMN CUSTS.TEL IS '전화';

COMMENT ON COLUMN CUSTS.DET_ADDR IS '상세주소';

COMMENT ON COLUMN CUSTS.A_NO IS '주소기본일련번호';

/* 제품정보 */
CREATE TABLE PRODS (
	P_NO INTEGER NOT NULL, /* 제품일련번호 */
	TITLE VARCHAR2(100) NOT NULL, /* 제품명 */
	MAKER VARCHAR2(60) NOT NULL, /* 제조사 */
	MADE_DT DATE NOT NULL, /* 제조일 */
	QNT INTEGER DEFAULT 0, /* 잔여수량 */
	PRIC NUMBER NOT NULL /* 가격 */
);

CREATE UNIQUE INDEX PK_PRODS
	ON PRODS (
		P_NO ASC
	);

ALTER TABLE PRODS
	ADD
		CONSTRAINT PK_PRODS
		PRIMARY KEY (
			P_NO
		);

COMMENT ON TABLE PRODS IS '제품정보';

COMMENT ON COLUMN PRODS.P_NO IS '제품일련번호';

COMMENT ON COLUMN PRODS.TITLE IS '제품명';

COMMENT ON COLUMN PRODS.MAKER IS '제조사';

COMMENT ON COLUMN PRODS.MADE_DT IS '제조일';

COMMENT ON COLUMN PRODS.QNT IS '잔여수량';

COMMENT ON COLUMN PRODS.PRIC IS '가격';

/* 주소기본정보 */
CREATE TABLE ADDRS (
	A_NO INTEGER NOT NULL, /* 주소기본일련번호 */
	PST_NO VARCHAR2(10) NOT NULL, /* 우편번호 */
	BAS_ADDR VARCHAR2(255) NOT NULL /* 기본주소 */
);

CREATE UNIQUE INDEX PK_ADDRS
	ON ADDRS (
		A_NO ASC
	);

ALTER TABLE ADDRS
	ADD
		CONSTRAINT PK_ADDRS
		PRIMARY KEY (
			A_NO
		);

COMMENT ON TABLE ADDRS IS '주소기본정보';

COMMENT ON COLUMN ADDRS.A_NO IS '주소기본일련번호';

COMMENT ON COLUMN ADDRS.PST_NO IS '우편번호';

COMMENT ON COLUMN ADDRS.BAS_ADDR IS '기본주소';

/* 고객추가정보 */
CREATE TABLE CUST_EX (
	C_ID VARCHAR2(20) NOT NULL, /* 고객아이디 */
	PHO_PAT VARCHAR2(255), /* 사진 */
	COMP VARCHAR2(60), /* 직장 */
	TITLE VARCHAR2(60), /* 직책 */
	TEL VARCHAR2(30), /* 전화 */
	FAX VARCHAR2(30), /* 팩스 */
	EMAIL VARCHAR2(40) /* 이메일 */
);

CREATE UNIQUE INDEX PK_CUST_EX
	ON CUST_EX (
		C_ID ASC
	);

ALTER TABLE CUST_EX
	ADD
		CONSTRAINT PK_CUST_EX
		PRIMARY KEY (
			C_ID
		);

COMMENT ON TABLE CUST_EX IS '고객추가정보';

COMMENT ON COLUMN CUST_EX.C_ID IS '고객아이디';

COMMENT ON COLUMN CUST_EX.PHO_PAT IS '사진';

COMMENT ON COLUMN CUST_EX.COMP IS '직장';

COMMENT ON COLUMN CUST_EX.TITLE IS '직책';

COMMENT ON COLUMN CUST_EX.TEL IS '전화';

COMMENT ON COLUMN CUST_EX.FAX IS '팩스';

COMMENT ON COLUMN CUST_EX.EMAIL IS '이메일';

ALTER TABLE ORDS
	ADD
		CONSTRAINT FK_CUSTS_TO_ORDS
		FOREIGN KEY (
			C_ID
		)
		REFERENCES CUSTS (
			C_ID
		);

ALTER TABLE ORDS
	ADD
		CONSTRAINT FK_PRODS_TO_ORDS
		FOREIGN KEY (
			P_NO
		)
		REFERENCES PRODS (
			P_NO
		);

ALTER TABLE PROD_PHOS
	ADD
		CONSTRAINT FK_PRODS_TO_PROD_PHOS
		FOREIGN KEY (
			P_NO
		)
		REFERENCES PRODS (
			P_NO
		);

ALTER TABLE CUSTS
	ADD
		CONSTRAINT FK_ADDRS_TO_CUSTS
		FOREIGN KEY (
			A_NO
		)
		REFERENCES ADDRS (
			A_NO
		);

ALTER TABLE CUST_EX
	ADD
		CONSTRAINT FK_CUSTS_TO_CUST_EX
		FOREIGN KEY (
			C_ID
		)
		REFERENCES CUSTS (
			C_ID
		);

DELETE ORDS;
DELETE PRODS;
DELETE CUSTS;
DELETE ADDRS;

DROP SEQUENCE ADDRS_SEQ;
DROP SEQUENCE PRODS_SEQ;
DROP SEQUENCE PROD_PHOS_SEQ;
DROP SEQUENCE ORDS_SEQ;

CREATE SEQUENCE ADDRS_SEQ;
CREATE SEQUENCE PRODS_SEQ;
CREATE SEQUENCE PROD_PHOS_SEQ;
CREATE SEQUENCE ORDS_SEQ;

INSERT INTO ADDRS (A_NO, PST_NO, BAS_ADDR)
VALUES (ADDRS_SEQ.nextval, '100-100', '경기도 용인시');

INSERT INTO ADDRS (A_NO, PST_NO, BAS_ADDR)
VALUES (ADDRS_SEQ.nextval, '100-101', '경기도 수원시');

INSERT INTO CUSTS (C_ID, PWD, EMAIL, C_NM, TEL, DET_ADDR, A_NO)
VALUES ('AAA','111','AAA@TEST.COM', 'AAA', '111-1111', '종로동', 1);

INSERT INTO CUSTS (C_ID, PWD, EMAIL, C_NM, TEL, DET_ADDR, A_NO)
VALUES ('BBB','111','BBB@TEST.COM', 'BBB', '111-1111', '원천동', 1);

INSERT INTO CUSTS (C_ID, PWD, EMAIL, C_NM, TEL, DET_ADDR, A_NO)
VALUES ('CCC','111','CCC@TEST.COM', 'CCC', '111-1111', '원천2동', 2);

INSERT INTO PRODS (P_NO, TITLE, MAKER, MADE_DT, QNT, PRIC)
VALUES (PRODS_SEQ.NEXTVAL, '아이폰5', '애플', '2012-08-09', 100, 890000);

INSERT INTO PRODS (P_NO, TITLE, MAKER, MADE_DT, QNT, PRIC)
VALUES (PRODS_SEQ.NEXTVAL, '아이폰4S', '애플', '2011-05-09', 60, 490000);

INSERT INTO PRODS (P_NO, TITLE, MAKER, MADE_DT, QNT, PRIC)
VALUES (PRODS_SEQ.NEXTVAL, '갤럭시4S', '삼성', '2012-10-09', 100, 990000);

INSERT INTO ORDS (O_NO, C_ID, P_NO, QNT, ORD_DT)
VALUES (ORDS_SEQ.NEXTVAL, 'AAA', 1, 5, '2013-05-05');

INSERT INTO ORDS (O_NO, C_ID, P_NO, QNT, ORD_DT)
VALUES (ORDS_SEQ.NEXTVAL, 'AAA', 2, 3, '2013-05-05');

INSERT INTO ORDS (O_NO, C_ID, P_NO, QNT, ORD_DT)
VALUES (ORDS_SEQ.NEXTVAL, 'BBB', 1, 15, '2013-06-05');